title: "🌎 Adolfo Andres Hincapie"
email: aahincap@unal.edu.co
timezone: UTC
baseurl: ''
permalink: "/:title/"
logo: 'assets/images/88x88.png' 
favicon: 'assets/images/favicon.ico'
author: Andrés Hincapié
paginate: 30
locale: en_us
lang: en_us
feed_items: 15
feed_update_period: daily
feed_update_frequency: 1
mermaid:
  src: 'https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js'
  theme: 'base'
  config:
    startOnLoad: true
    themeVariables:
      primaryColor: '#6c757d'
      primaryBorderColor: '#3d61fd'
      lineColor: '#000000'
      secondaryColor: '#08a057'
      tertiaryColor: '#fdd93d'
      primaryTextColor: '#ffffff'
      fontSize: '16px'
      edgeLabelBackground: '#08a057'
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-138701831-1

# Authors
authors:
  Andrés Hincapié:
    name: Andrés Hincapié
    display_name: Andrés H
    avatar: 'assets/images/minimal-avatars_new.svg'
    email: aahincap@unal.edu.co
    web: https://aahincapie.github.io
    twitter: https://twitter.com/
    linkedin: https://www.linkedin.com/in/aahincapie/
    description: "Geek author writing romance and mystery stories with a twist - carbon markets and climate change. Andres also likes to work on improving the methodology used to measure carbon. He likes to delve into the challenges of the market, such as the quality of projects, the role of governments, leakage and performance of the market."
  Copier:
    name: John Doe
    display_name: John Doe
    avatar: 'assets/images/john.png'
    email: john.doe@example.com
    web:  https://example.com
    twitter:  https://twitter.com/
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/aandreshinca/
  facebook: https://www.facebook.com/aahincapie
  twitter: https://twitter.com/aandreshinca/
  linkedin: https://www.linkedin.com/in/aahincapie/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-spaceship
- jekyll-mermaid
- jekyll-include-cache

# React build directory configuration
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - src
  - public
include:
  - _pages
  - assets
  - build