title: "🌎 Adolfo Andres Hincapie"
email: aahincap@unal.edu.co
timezone: UTC
baseurl: ''
permalink: "/:title/"
logo: 'assets/images/88x88.png' 
favicon: 'assets/images/favicon.ico'
author: Andres_Hincapie
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  Andrés Hincapié:
    name: Andrés Hincapié
    display_name: Andrés H
    avatar: 'assets/images/minimal-avatars.png'
    email: aahincap@unal.edu.co
    web: https://aahincapie.github.io
    twitter: https://twitter.com/aa_h1nc4p3
    linkedin: https://www.linkedin.com/in/aahincapie/
    description: "The author who walk slowly down and patiently through the carbon market and climate change. Andrés feels like have been here before, but each year is a old man and a the topic is a beautiful young lady. The author provide comprehensive information to support the efficient development of the carbon markets, new methodologies, and the development and operation of carbon projects, as well as other carbon-related issues."
  john:
    name: John
    display_name: John
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/aa_h1nc4p3/
  facebook: https://www.facebook.com/aahincapie
  twitter: https://twitter.com/aa_h1nc4p3
  linkedin: https://www.linkedin.com/in/aahincapie/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
